---
- hosts: localhost
  sudo: yes
  tasks:

    - name: Debug
      debug: msg="ansible_os_family={{ansible_os_family}} ansible_distribution_version={{ansible_distribution_version}}"
      sudo: no

# Dev Tools
    - name: Install tig
      dnf: name=tig state=latest
    - name: Install Ruby
      action: dnf name={{ item }} state=installed
      with_items:
        - rubypick
        - ruby
        - rubygem-bundler

# Sabma
    - name: Install Samba
      action: dnf name={{ item }} state=installed
      with_items:
        - samba
        - samba-client
    - name: create a directory to share
      file: path=/opt/samba/ mode=0755 state=directory
    - name: add a share
      lineinfile: dest=/etc/samba/smb.conf regexp='' insertafter=EOF line='[samba]\n\tpath = /opt/samba/\n\tread only = no\n\tbrowseable = yes\n'
    - name: set selinux boolean
      command: /usr/sbin/setsebool -P allow_smbd_anon_write=1
    - name: allow full access (r/w)
      command: /usr/sbin/setsebool -P samba_export_all_rw on
    - name: set selinux context
      command: /usr/bin/chcon -t samba_share_t /opt/samba/
    - name: start samba
      service: name=smb state=running enabled=yes
    - name: start named
      service: name=nmb state=running enabled=yes
    - name: configure firewall, allow samba traffic
      firewalld: service=samba permanent=true state=enabled
# @TODO: make the services start rather then just start on boot

# Optional Bits
#   InfluxDB (https://influxdb.com/docs/v0.9/introduction/getting_started.html)
    - name: InfluxDB download
      get_url: url=http://influxdb.s3.amazonaws.com/influxdb-0.9.4.2-1.x86_64.rpm dest=/tmp/influxdb-0.9.4.2-1.x86_64.rpm mode=0660
    - name: InfluxDB install
      dnf: name=/tmp/influxdb-0.9.4.2-1.x86_64.rpm state=present
    - name: InfluxDB start
      service: name=influxdb state=running enabled=yes
    - name: InfluxDB firewall 8083
      firewalld: port=8083/tcp permanent=true state=enabled
    - name: InfluxDB firewall 8086
      firewalld: port=8086/tcp permanent=true state=enabled
    - name: InfluxDB admin interface
      debug: msg="http://{{ansible_default_ipv4.address}}:8083/"
      sudo: no
# @TODO: add Grafana to Influx (http://docs.grafana.org/installation/rpm/)

    - name: Manual steps
      debug: msg="Add your local user to samba by `sudo smbpasswd -a {yourUserName}`"
      sudo: no
